// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs9cSFy9YRe5lNAuKwoMnnfR0OVtHno2Y',
    appId: '1:1072644343372:web:17180d3eab568b079ad6e9',
    messagingSenderId: '1072644343372',
    projectId: 'evently-app-441f0',
    authDomain: 'evently-app-441f0.firebaseapp.com',
    storageBucket: 'evently-app-441f0.firebasestorage.app',
    measurementId: 'G-S77V905ZL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYRK7V-ejMkkM53oPFkUNRPrll-oR7BLI',
    appId: '1:1072644343372:android:9e4512a2ec8432d39ad6e9',
    messagingSenderId: '1072644343372',
    projectId: 'evently-app-441f0',
    storageBucket: 'evently-app-441f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH-YQtiTCQ_mSvEnePccEWZ8dWO5XcRKE',
    appId: '1:1072644343372:ios:48a7fb48165605db9ad6e9',
    messagingSenderId: '1072644343372',
    projectId: 'evently-app-441f0',
    storageBucket: 'evently-app-441f0.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH-YQtiTCQ_mSvEnePccEWZ8dWO5XcRKE',
    appId: '1:1072644343372:ios:48a7fb48165605db9ad6e9',
    messagingSenderId: '1072644343372',
    projectId: 'evently-app-441f0',
    storageBucket: 'evently-app-441f0.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs9cSFy9YRe5lNAuKwoMnnfR0OVtHno2Y',
    appId: '1:1072644343372:web:d55a5157c9ea7b6c9ad6e9',
    messagingSenderId: '1072644343372',
    projectId: 'evently-app-441f0',
    authDomain: 'evently-app-441f0.firebaseapp.com',
    storageBucket: 'evently-app-441f0.firebasestorage.app',
    measurementId: 'G-8KHN14R0RQ',
  );
}
